services:
  django-web:
    build: .
    container_name: django-docker
    ports:
      - "8000:8000"
#   depends_on:
    volumes:
      - ./.data/db.sqlite3:/app/db.sqlite3
      - ./.data/migrations:/app/journalmain/migrations
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SIGNAL_NUMBER: ${SIGNAL_NUMBER}
      WEBAPP_USERNAME: ${WEBAPP_USERNAME}
      DEBUG: ${DJANGO_DEBUG}
  signal-cli-rest-api:
    container_name: signal-api
    restart: always
    ports:
      - 8080:8080
    volumes:
      - $HOME/.local/share/signal-api:/home/.local/share/signal-cli
    environment:
      - MODE=native
    image: bbernhard/signal-cli-rest-api
  ollama-intel-gpu:
    build:
      context: .
      dockerfile: ollama-dockerfile
      args:
        IPEXLLM_RELEASE_REPO: ipex-llm/ipex-llm
        IPEXLLM_RELEASE_VERSON: v2.2.0
        IPEXLLM_PORTABLE_ZIP_FILENAME: ollama-ipex-llm-2.2.0-ubuntu.tgz
    container_name: ollama-intel-gpu
    restart: always
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ollama-intel-gpu:/root/.ollama
    environment:
      - ONEAPI_DEVICE_SELECTOR=level_zero:0
      - IPEX_LLM_NUM_CTX=16384
      - OLLAMA_CONTEXT_LENGTH=16384
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ollama-webui:/app/backend/data
    depends_on:
      - ollama-intel-gpu
    ports:
      - ${OLLAMA_WEBUI_PORT-3000}:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama-intel-gpu:11434
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
volumes:
  ollama-webui: {}
  ollama-intel-gpu: {}
