from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import JournalEntry
import json
# Create your views here.


# Simple helper function:
mood_colors = {
    "happy": "badge-primary",
    "sad": "badge-secondary",
    "angry": "badge-danger",
    "afraid": "badge-warning",
    "excited": "badge-success",
    "calm": "badge-info",
    "worried": "badge-light",
    "in love": "badge-danger",
    "surprised": "badge-warning",
    "proud": "badge-success",
    "ashamed": "badge-secondary",
    "frustrated": "badge-danger",
    "guilty": "badge-danger",
    "curious": "badge-info",
    "nostalgic": "badge-light",
    "hopeful": "badge-primary",
    "disappointed": "badge-secondary",
    "embarrassed": "badge-secondary",
    "envious": "badge-danger",
    "grateful": "badge-success",
    "longing": "badge-info",
    "relieved": "badge-primary",
    "optimistic": "badge-primary",
    "pessimistic": "badge-dark"
}

def mood_list_creation(entry: JournalEntry):
    return_list = []
    if(entry.mood is None):
        print('Journal is yet to be processed by AI')
        return ['<span class="badge badge-pill badge-light">Journal is yet to be processed by AI</span>']
    else:
        # We expect that entry.mood is a valid python array
        try:
            # Hacky way of doing this, but, this is the best I can think of
            print(json.loads(entry.mood.replace("'", '"'))) # AI will generate the list with either ' or ", this fixes it
            moodl = json.loads(entry.mood.replace("'", '"'))
            for element in moodl:
                print(element)
                if mood_colors.get(element) is not None:
                    return_list.append(f'<span class="badge badge-pill {mood_colors.get(element)}">{element}</span>')
        except:
           return ['<span class="badge badge-pill badge-danger">Mood list generated by AI is invalid</span>']
    print(return_list)
    return return_list

def journals(request):
    journal_entries = JournalEntry.objects.all()
    return render(request, 'journalindex.html', {'journal_entries': journal_entries}) #HttpResponse("Hello world!")

def journal_detail(request, id):
    entry = get_object_or_404(JournalEntry, id=id)
    mood = mood_list_creation(entry)
    print(mood)
    return render(request, 'journal_detail.html', {'entry': entry, 'moods' : mood})
